# Generated by Django 6.0.2
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, help_text='User role at the time of the action (stored for historical accuracy)', max_length=20)),
                ('user_name', models.CharField(blank=True, help_text="User's full name at the time of the action", max_length=200)),
                ('action', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('VIEW', 'VIEW'), ('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('DOWNLOAD', 'DOWNLOAD'), ('PRINT', 'PRINT'), ('EXPORT', 'EXPORT')], db_index=True, max_length=20)),
                ('module', models.CharField(choices=[('Authentication', 'Authentication'), ('Patients', 'Patients'), ('Appointments', 'Appointments'), ('Consultations', 'Consultations'), ('Medical Certificates', 'Medical Certificates'), ('Dental Certificates', 'Dental Certificates'), ('Reports', 'Reports'), ('User Management', 'User Management'), ('Settings', 'Settings'), ('Certificate Templates', 'Certificate Templates'), ('Inventory', 'Inventory'), ('Feedback', 'Feedback')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True, help_text='Human-readable explanation of the activity')),
                ('object_model', models.CharField(blank=True, help_text='Dotted model path (e.g. "patients.Patient")', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='Primary key / identifier of the affected record', max_length=50)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the affected object', max_length=300)),
                ('changes_before', models.JSONField(blank=True, help_text='Snapshot of values BEFORE the change (dict)', null=True)),
                ('changes_after', models.JSONField(blank=True, help_text='Snapshot of values AFTER the change (dict)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Request IP address when available', null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], db_index=True, default='SUCCESS', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'managed': True,
                'indexes': [
                    models.Index(fields=['-timestamp'], name='audit_log_timestamp_idx'),
                    models.Index(fields=['user', '-timestamp'], name='audit_log_user_ts_idx'),
                    models.Index(fields=['user_role', '-timestamp'], name='audit_log_role_ts_idx'),
                    models.Index(fields=['action', 'module'], name='audit_log_action_mod_idx'),
                    models.Index(fields=['module', '-timestamp'], name='audit_log_module_ts_idx'),
                    models.Index(fields=['status', '-timestamp'], name='audit_log_status_ts_idx'),
                    models.Index(fields=['object_model', 'object_id'], name='audit_log_object_idx'),
                ],
            },
        ),
    ]
