# Generated by Django 6.0.4 on 2026-07-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__timesta_63825c_idx',
            old_name='audit_log_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__user_id_64dfe5_idx',
            old_name='audit_log_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__user_ro_66e0c7_idx',
            old_name='audit_log_role_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__action_6eaf81_idx',
            old_name='audit_log_action_mod_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__module_7b7e44_idx',
            old_name='audit_log_module_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__status_bdfe51_idx',
            old_name='audit_log_status_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__object__535fa7_idx',
            old_name='audit_log_object_idx',
        ),
    ]
