# Generated by Django 6.0.4 on 2026-07-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0003_remove_dental_certificates_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('Authentication', 'Authentication'), ('Patients', 'Patients'), ('Appointments', 'Appointments'), ('Consultations', 'Consultations'), ('Medical Certificates', 'Medical Certificates'), ('Reports', 'Reports'), ('User Management', 'User Management'), ('Settings', 'Settings'), ('Certificate Templates', 'Certificate Templates'), ('Inventory', 'Inventory'), ('Feedback', 'Feedback')], db_index=True, max_length=30),
        ),
    ]
