"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from decouple import config
from pathlib import Path

# ── Redis / Cache ──────────────────────────────────────────────────────────
# django-redis configuration used for both caching and session storage.
# Requires django-redis to be installed (see requirements.txt).
REDIS_URL = config('REDIS_URL', default='redis://127.0.0.1:6379/1')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # Ignores connection test errors so Django can start without Redis
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'cpr',
    }
}

# Store Django sessions in Redis (via the cache backend) for fast reads/writes
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [h.strip() for h in config('ALLOWED_HOSTS', default='').split(',') if h.strip()]

# ── CSRF Trusted Origins ──────────────────────────────────────────────────
# Required for Cloudflare tunnels and other proxy setups that inject an
# Origin header different from the Host header (e.g. trycloudflare.com).
#
# Set explicitly in .env as a comma-separated list (with scheme) to override.
# Examples:
#   CSRF_TRUSTED_ORIGINS=https://*.trycloudflare.com
#   CSRF_TRUSTED_ORIGINS=http://localhost:8000,https://my.domain.com
#
# If not set (default), CSRF_TRUSTED_ORIGINS is derived from ALLOWED_HOSTS
# with both http:// and https:// schemes, so local Docker deployments work
# out of the box. Cloudflare tunnel users MUST set it explicitly since the
# tunnel URL changes every session.
_trusted_origins = config('CSRF_TRUSTED_ORIGINS', default='')
if _trusted_origins:
    CSRF_TRUSTED_ORIGINS = [h.strip() for h in _trusted_origins.split(',') if h.strip()]
else:
    # Derive both http and https variants from ALLOWED_HOSTS
    _allowed = [h for h in ALLOWED_HOSTS if h and h != '*']
    CSRF_TRUSTED_ORIGINS = [
        f"https://{h}" for h in _allowed
    ] + [
        f"http://{h}" for h in _allowed
    ]
    # Also allow common Cloudflare tunnel domain as a convenience for users
    # who access via trycloudflare.com without setting the env var.
    CSRF_TRUSTED_ORIGINS.append('https://*.trycloudflare.com')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'patients',
    'consultations',
    'colleges',
    'inventory',
    'certificates',
    'reports',
    'core',
    'notifications',
    'feedback',
    'audit_logs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.IdleSessionTimeoutMiddleware',
    'accounts.middleware.ProfileCompletionMiddleware',
    'audit_logs.middleware.AuditIPMiddleware',
]


EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = 'smtp.gmail.com'
EMAIL_USE_TLS       = False
EMAIL_USE_SSL       = True
EMAIL_PORT          = 465
EMAIL_HOST_USER     = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL  = config('EMAIL_HOST_USER')
EMAIL_TIMEOUT       = 10  # seconds — fail fast if SMTP is unreachable or unresponsive
AUTH_USER_MODEL = 'accounts.User'

# FIX: LOGIN_URL, LOGIN_REDIRECT_URL, and LOGOUT_REDIRECT_URL must be URL
# *paths*, not URL *names*. Django's auth middleware does not resolve named
# URLs for these settings — passing 'accounts:login' sends users to the
# literal path "/accounts:login" which doesn't exist, causing the broken
# redirect you were seeing.
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.idle_session_timeout',
            ],
        },
    },
]

ROOT_URLCONF = 'main.urls'
WSGI_APPLICATION = 'main.wsgi.application'

DB_ENGINE = config("DB_ENGINE", default="sqlite")

if DB_ENGINE == "mysql":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config("DB_NAME"),
            'USER': config("DB_USER"),
            'PASSWORD': config("DB_PASSWORD"),
            'HOST': config("DB_HOST"),
            'PORT': config("DB_PORT"),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / "db.sqlite3",
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Manila'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# ── Media (uploaded files) ──────────────────────────────────────────────
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from django.contrib.messages import constants as messages_constants

MESSAGE_TAGS = {
    messages_constants.DEBUG: 'info',
    messages_constants.INFO: 'info',
    messages_constants.SUCCESS: 'success',
    messages_constants.WARNING: 'warning',
    messages_constants.ERROR: 'error',
}

# ── Production security settings ────────────────────────────────────────
# For local-network HTTP deployments (Docker, no domain, no HTTPS), these
# default to safe HTTP-friendly values. Override via .env if deploying
# behind a real HTTPS proxy.
#
# IMPORTANT: When DEBUG=False, cookies default to Secure=True which breaks
# HTTP access. Set SESSION_COOKIE_SECURE=0 and CSRF_COOKIE_SECURE=0 in .env
# if you are NOT using HTTPS.
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
# Only trust X-Forwarded-Proto when behind a proxy. Avoids false HTTPS
# detection from browser extensions or Docker networking quirks.
SECURE_PROXY_SSL_HEADER = config('SECURE_PROXY_SSL_HEADER', default=None, cast=lambda v: ('HTTP_X_FORWARDED_PROTO', 'https') if v and v not in ('0', 'false', 'False') else None)

# ── Session & idle timeout ────────────────────────────────────────────────
# Server-side session expiry. Must be >= IDLE_SESSION_TIMEOUT_MINUTES so the
# session data (including last_activity) doesn't vanish before the idle check.
SESSION_COOKIE_AGE = 86400  # 24 hours (seconds) — longer than idle timeout so the idle check is the effective limiter

# After this many minutes of inactivity, the user is automatically logged out.
# Set to 0 or None to disable idle timeout.
IDLE_SESSION_TIMEOUT_MINUTES = 720