# Generated by Django 6.0.4 on 2026-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Students'", max_length=80)),
                ('subtitle', models.CharField(help_text="e.g. 'Primary health care'", max_length=120)),
                ('icon', models.CharField(default='fa-user', help_text='Font Awesome class.', max_length=60)),
                ('icon_color', models.CharField(default='#2563eb', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Card',
                'verbose_name_plural': 'About Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='About', max_length=80)),
                ('headline', models.CharField(default='NORSU Medical Dental Clinic', max_length=140)),
                ('description_1', models.TextField(default='Committed to providing quality, accessible healthcare services to the entire university community — students, faculty, staff, and dependents.')),
                ('description_2', models.TextField(default='Our digital system streamlines the patient experience — from registration and triage to doctor consultation, prescription dispensing, and follow-up care.')),
            ],
            options={
                'verbose_name': 'About Content',
                'verbose_name_plural': 'About Content',
            },
        ),
        migrations.CreateModel(
            name='AboutPill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('icon', models.CharField(default='fa-check', help_text="Font Awesome class e.g. 'fa-shield-halved'", max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Pill',
                'verbose_name_plural': 'About Pills',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Contact', max_length=80)),
                ('headline', models.CharField(default='Get in Touch', max_length=140)),
                ('subtext', models.CharField(default='Have questions or need assistance? Reach out to the NORSU Medical Dental Clinic.', max_length=220)),
            ],
            options={
                'verbose_name': 'Contact Section Header',
                'verbose_name_plural': 'Contact Section Header',
            },
        ),
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Location', 'Hours', 'Email'", max_length=80)),
                ('detail', models.TextField(help_text='Contact detail text shown on the card.')),
                ('icon', models.CharField(default='fa-map-marker-alt', help_text='Font Awesome class.', max_length=60)),
                ('icon_bg', models.CharField(default='#eff6ff', max_length=30)),
                ('icon_color', models.CharField(default='#2563eb', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contact Item',
                'verbose_name_plural': 'Contact Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(help_text='Short description shown on the card.')),
                ('tag', models.CharField(default='Core', help_text="Small pill tag (e.g. 'Records', 'Workflow', 'Analytics').", max_length=40)),
                ('icon', models.CharField(default='fa-circle', help_text="Font Awesome class without 'fa-' prefix is fine, but store full class e.g. 'fa-users'.", max_length=60)),
                ('icon_bg', models.CharField(default='#eff6ff', help_text='Icon background colour (hex or CSS colour).', max_length=30)),
                ('icon_color', models.CharField(default='#2563eb', help_text='Icon foreground colour (hex or CSS colour).', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature Card',
                'verbose_name_plural': 'Feature Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeaturesContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Features', max_length=80)),
                ('headline', models.CharField(default='Everything You Need', max_length=140)),
                ('subtext', models.CharField(default='Powerful tools to streamline your clinic operations from registration to discharge.', max_length=220)),
            ],
            options={
                'verbose_name': 'Features Section Header',
                'verbose_name_plural': 'Features Section Header',
            },
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='NORSU — Medical Dental Clinic', help_text="Small badge above the headline (e.g. 'NORSU — Medical Dental Clinic').", max_length=120)),
                ('headline_plain', models.CharField(default='Your Health,', help_text='First line of the hero headline (plain colour).', max_length=120)),
                ('headline_accent', models.CharField(default='Digitally Managed', help_text='Second line of the hero headline (gradient colour).', max_length=120)),
                ('description', models.TextField(default='A seamless consultation management system for students, staff, and faculty. From triage to prescription — all in one place.', help_text='Short paragraph below the headline.')),
                ('cta_primary_label', models.CharField(default='Sign In', help_text='Label for the primary CTA button (links to login).', max_length=60)),
                ('cta_secondary_label', models.CharField(default='Explore Features', help_text='Label for the secondary CTA button (scrolls to #features).', max_length=60)),
            ],
            options={
                'verbose_name': 'Hero Content',
                'verbose_name_plural': 'Hero Content',
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="e.g. '10k+', '24/7', '4+'", max_length=20)),
                ('label', models.CharField(help_text="e.g. 'Records', 'Access', 'Clinics'", max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (ascending).')),
            ],
            options={
                'verbose_name': 'Hero Stat',
                'verbose_name_plural': 'Hero Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Clinic Recorder', help_text='Brand name shown in the navbar and footer.', max_length=100)),
                ('site_title', models.CharField(default='Clinic Recorder — NORSU Medical Dental Clinic', help_text='Browser tab title for the home page.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StatStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="e.g. '10k+', '50+'", max_length=20)),
                ('label', models.CharField(help_text="e.g. 'Patient Records'", max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stats Strip Item',
                'verbose_name_plural': 'Stats Strip',
                'ordering': ['order'],
            },
        ),
    ]
