# Generated by Django 6.0.4 on 2026-04-29 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0004_triage_oxygen_saturation_triage_respiratory_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='Diagnosis for the certificate')),
                ('rest_from', models.DateField(help_text='Rest period start date')),
                ('rest_to', models.DateField(help_text='Rest period end date')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or restrictions')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='consultations.consultation')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Certificate',
                'verbose_name_plural': 'Medical Certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
