# Generated by Django 6.0.4 on 2026-04-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcertificate',
            name='certificate_type',
            field=models.CharField(choices=[('standard', 'Medical Certificate'), ('fit_to_play', 'Fit-to-Play Certificate'), ('fit_to_work', 'Fit-to-Work Certificate'), ('dental', 'Dental Certificate')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='rest_from',
            field=models.DateField(blank=True, help_text='Rest period start date', null=True),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='rest_to',
            field=models.DateField(blank=True, help_text='Rest period end date', null=True),
        ),
    ]
