# Generated by Django 6.0.4 on 2026-06-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_medicalcertificate_status_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicalcertificate',
            new_name='certificate_status_579324_idx',
            old_name='certificate_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalcertificate',
            new_name='certificate_certifi_bba2bf_idx',
            old_name='certificate_number_idx',
        ),
    ]
