# Generated by Django 6.0.4 on 2026-06-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_rename_certificate_status_created_idx_certificate_status_579324_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplateText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('standard', 'Medical Certificate'), ('fit_to_play', 'Fit-to-Play Certificate'), ('fit_to_work', 'Fit-to-Work Certificate'), ('dental', 'Dental Certificate')], max_length=20)),
                ('slot_key', models.CharField(help_text='Unique identifier for this prose slot (e.g. diagnosis_statement)', max_length=50)),
                ('text', models.TextField(help_text='Prose text with {placeholder} tokens for dynamic values')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Certificate Template Text',
                'verbose_name_plural': 'Certificate Template Texts',
                'unique_together': {('certificate_type', 'slot_key')},
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplateChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_text', models.TextField(blank=True)),
                ('new_text', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='certificates.certificatetemplatetext')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Certificate Template Change Log',
                'verbose_name_plural': 'Certificate Template Change Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='rendered_text_snapshot',
            field=models.JSONField(blank=True, help_text='Resolved prose text at time of issuance (keyed by slot_key)', null=True),
        ),
    ]
