# Generated by Django 6.0.4 on 2026-07-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_consolidate_template_text_into_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='rendered_text_snapshot',
            field=models.JSONField(blank=True, help_text='Resolved body text at time of issuance (single string)', null=True),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='template_version',
            field=models.CharField(default='3.0', help_text='Print template version used', max_length=10),
        ),
    ]
