# Generated by Django 6.0.4 on 2026-07-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_alter_medicalcertificate_rendered_text_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplatetext',
            name='certificate_type',
            field=models.CharField(choices=[('standard', 'Medical Certificate-Absences of classes-work'), ('fit_to_play', 'Medical Certificate_Activitiest-training-seminars'), ('fit_to_work', 'Medical Certificate-OJT'), ('dental', 'Dental Certificate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='certificate_type',
            field=models.CharField(choices=[('standard', 'Medical Certificate-Absences of classes-work'), ('fit_to_play', 'Medical Certificate_Activitiest-training-seminars'), ('fit_to_work', 'Medical Certificate-OJT'), ('dental', 'Dental Certificate')], default='standard', max_length=20),
        ),
    ]
