# Generated by Django 6.0.4 on 2026-07-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_alter_certificatetemplatetext_certificate_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplatetext',
            name='certificate_type',
            field=models.CharField(choices=[('standard', 'Medical Certificate-Absences  of classes-work'), ('fit_to_work', 'Medical Certificate-OJT'), ('fit_to_play', 'Medical Certificate_Activitiest-training-seminars')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='certificate_type',
            field=models.CharField(choices=[('standard', 'Medical Certificate-Absences  of classes-work'), ('fit_to_work', 'Medical Certificate-OJT'), ('fit_to_play', 'Medical Certificate_Activitiest-training-seminars')], default='standard', max_length=20),
        ),
    ]
