# Generated by Django 6.0.4 on 2026-04-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
