# Generated by Django 6.0.4 on 2026-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_force_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('frontdesk', 'Front Desk'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
