# Generated by Django 6.0.4 on 2026-04-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['role', 'username'], 'verbose_name': 'Staff User', 'verbose_name_plural': 'Staff Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('nurse', 'Nurse'), ('doctor', 'Doctor'), ('frontdesk', 'Front Desk'), ('admin', 'Admin')], default='nurse', max_length=10),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
