# Generated by Django 6.0.4 on 2026-04-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['role', 'username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('frontdesk', 'Front Desk'), ('admin', 'Admin')], default='nurse', max_length=10),
        ),
    ]
