# Generated by Django 6.0.4 on 2026-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_failed_login_attempts_user_locked_until_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reset_token_expiry',
            new_name='reset_otp_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_token',
        ),
        migrations.AddField(
            model_name='user',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
