# Generated by Django 6.0.4 on 2026-05-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_reset_token_expiry_user_reset_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('frontdesk', 'Front Desk'), ('admin', 'Admin')], default='patient', max_length=10),
        ),
    ]
