# Generated by Django 6.0.4 on 2026-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('frontdesk', 'Front Desk'), ('admin', 'Admin')], default='patient', max_length=10),
        ),
    ]
