# Generated by Django 6.0.4 on 2026-05-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional profile picture (JPG, PNG, WebP)', null=True, upload_to='staff/'),
        ),
    ]
