# Generated by Django 6.0.4 on 2026-05-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
