# Generated by Django 6.0.4

from django.db import migrations, models


def fix_empty_emails(apps, schema_editor):
    """Convert users with email='' to email=NULL to avoid MySQL unique constraint violations."""
    User = apps.get_model('accounts', 'User')
    empty_email_users = User.objects.filter(email='')
    count = empty_email_users.count()
    if count:
        # Can't update with email=None directly in the queryset because
        # MySQL treats '' and NULL differently. We use update() with None.
        empty_email_users.update(email=None)
        print(f"  ↳ Fixed {count} user(s) with empty email.")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_temp_password'),
    ]

    operations = [
        migrations.RunPython(fix_empty_emails, reverse_code=migrations.RunPython.noop),
    ]
