# Generated by Django 6.0.7 on 2026-09-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_fix_empty_email_to_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, help_text='Credentials / suffix (e.g. M.D., R.N., Ph.D.)', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, help_text='Title / prefix (e.g. Dr., Mr., Ms., Atty.)', max_length=20),
        ),
    ]
