# Generated by Django 6.0.4 on 2026-04-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='severity_description',
            field=models.TextField(help_text='Self-reported severity description by the patient'),
        ),
    ]
