# Generated by Django 6.0.4 on 2026-04-28 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_patient_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(blank=True, help_text='e.g. 500mg, 10ml', max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 7 days, until finished', max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(blank=True, help_text='e.g. 3x a day, once daily', max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine_name',
            field=models.CharField(blank=True, help_text='Free-text medicine name', max_length=200),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.CharField(blank=True, help_text='e.g. Take after meals', max_length=200),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='inventory.medicine'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
