# Generated by Django 6.0.4 on 2026-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_prescriptionitem_dosage_prescriptionitem_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='oxygen_saturation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Oxygen saturation (SpO2) percentage (e.g. 98.50)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='triage',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Respiratory rate (breaths per minute)', null=True),
        ),
        migrations.AddField(
            model_name='triage',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms (e.g. 65.50)', max_digits=5, null=True),
        ),
    ]
