# Generated by Django 6.0.4 on 2026-05-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_triage_oxygen_saturation_triage_respiratory_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g. Respiratory, Musculoskeletal, etc.', max_length=100)),
            ],
            options={
                'verbose_name': 'Common Diagnosis',
                'verbose_name_plural': 'Common Diagnoses',
                'ordering': ['name'],
            },
        ),
    ]
