# Generated by Django 6.0.4 on 2026-05-14 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_commondiagnosis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='When the consultation case was closed', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='closure_notes',
            field=models.TextField(blank=True, help_text='Reason/notes for closing the consultation case'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of follow-up visits for this case'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_original_case',
            field=models.BooleanField(default=True, help_text='True if this is the initial consultation (case file)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='last_follow_up_date',
            field=models.DateTimeField(blank=True, help_text='Date of the most recent follow-up', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='parent_consultation',
            field=models.ForeignKey(blank=True, help_text='Link to the original consultation if this is a follow-up', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_visits', to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('scheduled', 'Scheduled'), ('triaged', 'Triaged'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('active_follow_up', 'Active - Follow-up'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triages', to='consultations.consultation'),
        ),
        migrations.CreateModel(
            name='FollowUpProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.PositiveIntegerField(help_text='Sequential number of this follow-up visit (1, 2, 3...)')),
                ('symptoms', models.TextField(help_text='Current symptoms reported during this follow-up')),
                ('assessment', models.TextField(blank=True, help_text='Doctor assessment for this visit')),
                ('treatment_notes', models.TextField(blank=True, help_text='Treatment administered or adjusted during this visit')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for the patient after this visit')),
                ('notes', models.TextField(blank=True, help_text='Additional notes specific to this follow-up visit')),
                ('follow_up_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('requires_follow_up', models.BooleanField(default=False, help_text='Whether another follow-up is needed after this visit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(help_text='The original consultation case this follow-up belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='consultations.consultation')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_visits_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow-up Progress Entry',
                'verbose_name_plural': 'Follow-up Progress Entries',
                'ordering': ['consultation', '-visit_number'],
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='follow_up_progress',
            field=models.ForeignKey(blank=True, help_text='Link to specific follow-up visit if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.followupprogress'),
        ),
        migrations.AddField(
            model_name='triage',
            name='follow_up_progress',
            field=models.ForeignKey(blank=True, help_text='Link to specific follow-up visit if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triages', to='consultations.followupprogress'),
        ),
        migrations.AddIndex(
            model_name='followupprogress',
            index=models.Index(fields=['consultation', '-visit_number'], name='consultatio_consult_f7b792_idx'),
        ),
        migrations.AddIndex(
            model_name='followupprogress',
            index=models.Index(fields=['follow_up_status', '-created_at'], name='consultatio_follow__1bf8c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='followupprogress',
            unique_together={('consultation', 'visit_number')},
        ),
    ]
