# Generated by Django 6.0.4 on 2026-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_consultation_closed_at_consultation_closure_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='recommended_follow_up_date',
            field=models.DateField(blank=True, help_text='Recommended date for the next follow-up visit', null=True),
        ),
    ]
