# Generated by Django 6.0.4 on 2026-05-14 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_consultation_recommended_follow_up_date'),
        ('patients', '0004_patientprofile_arthritis_patientprofile_asthma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('queue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(help_text='The original consultation case this follow-up request belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_requests', to='consultations.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_requests', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Follow-up Request',
                'verbose_name_plural': 'Follow-up Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_status', '-created_at'], name='consultatio_request_2fd086_idx'), models.Index(fields=['consultation', '-created_at'], name='consultatio_consult_09aa9d_idx')],
            },
        ),
    ]
