# Generated by Django 6.0.4 on 2026-05-18 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_followuprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triage',
            name='nurse',
        ),
        migrations.AddField(
            model_name='triage',
            name='triaged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages_performed', to=settings.AUTH_USER_MODEL, verbose_name='Triaged by'),
        ),
    ]
