# Generated by Django 6.0.4 on 2026-08-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_remove_triage_nurse_triage_triaged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='chief_complaint',
            field=models.TextField(blank=True, help_text="Doctor-reviewed final chief complaint. When empty, the patient's own words (symptoms) are shown on official documents."),
        ),
    ]
