# Generated by Django 6.0.4 on 2026-08-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_consultation_chief_complaint'),
        ('patients', '0008_patient_temp_password'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'queued', 'scheduled', 'triaged', 'active_follow_up'))), fields=('patient',), name='unique_active_consultation_per_patient'),
        ),
    ]
