# Generated by Django 6.0.4 on 2026-08-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0011_consultation_unique_active_consultation_per_patient'),
        ('patients', '0008_patient_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='active_flag',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(status__in=('pending', 'queued', 'scheduled', 'triaged', 'active_follow_up'), then=models.Value(1)), default=None, output_field=models.IntegerField()), output_field=models.IntegerField(blank=True, null=True)),
        ),
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.UniqueConstraint(fields=('patient', 'active_flag'), name='unique_active_consultation_per_patient_mysql'),
        ),
    ]
