# Generated by Django 6.0.4 on 2026-08-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0012_consultation_active_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triage',
            name='urgency',
        ),
    ]
