# Generated by Django 6.0.4 on 2026-04-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Medicine name (e.g., Paracetamol 500mg)', max_length=200, unique=True)),
                ('generic_name', models.CharField(blank=True, help_text='Generic/chemical name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Uses, side effects, etc.')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity')),
                ('unit', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup (ml)'), ('injection', 'Injection (ml)'), ('powder', 'Powder (g)'), ('cream', 'Cream (g)'), ('drops', 'Drops (ml)'), ('piece', 'Piece')], default='tablet', max_length=20)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this')),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price per unit', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='inventory_m_name_7f2fd2_idx'), models.Index(fields=['quantity'], name='inventory_m_quantit_3cd49e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('expired', 'Expired/Removed')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, help_text='Why stock was added/removed', max_length=200)),
                ('reference', models.CharField(blank=True, help_text='Consultation ID, receipt number, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, help_text='Username of who made the movement', max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.medicine')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['medicine', '-created_at'], name='inventory_s_medicin_398238_idx')],
            },
        ),
    ]
