# Generated by Django 6.0.4 on 2026-04-28 06:04

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email address', max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Name of emergency contact', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Phone number of emergency contact', max_length=30, validators=[patients.models.validate_phone]),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary contact number (e.g. 09171234567)', max_length=30, validators=[patients.models.validate_phone]),
        ),
    ]
