# Generated by Django 6.0.4 on 2026-04-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('patients', '0002_patient_email_patient_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='has_logged_in',
            field=models.BooleanField(db_index=True, default=False, help_text='True once the patient has successfully logged into the system at least once.'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Home address', max_length=300),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], help_text='Blood type', max_length=10),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='existing_conditions',
            field=models.TextField(blank=True, help_text='Existing medical conditions (e.g. diabetes, hypertension)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='known_allergies',
            field=models.TextField(blank=True, help_text='List any known allergies (medications, food, etc.)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='True once the patient has completed the mandatory profile setup.'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['has_logged_in'], name='patients_pa_has_log_23d631_idx'),
        ),
    ]
