# Generated by Django 6.0.4 on 2026-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_has_logged_in_patientprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='arthritis',
            field=models.BooleanField(default=False, help_text='Patient has arthritis'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='asthma',
            field=models.BooleanField(default=False, help_text='Patient has asthma'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='bcg',
            field=models.BooleanField(default=False, help_text='BCG vaccine received'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='cardiac_problems',
            field=models.BooleanField(default=False, help_text='Patient has cardiac problems'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], help_text='Civil status', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True, help_text='List of current medications and dosages'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='diabetes',
            field=models.BooleanField(default=False, help_text='Patient has diabetes'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='dpt',
            field=models.BooleanField(default=False, help_text='DPT vaccine received'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in centimeters', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hepatitis_b',
            field=models.BooleanField(default=False, help_text='Hepatitis B vaccine received'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hypertension',
            field=models.BooleanField(default=False, help_text='Patient has hypertension'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='immunization_others',
            field=models.TextField(blank=True, help_text='Other immunization details (e.g. influenza, HPV, etc.)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='measles',
            field=models.BooleanField(default=False, help_text='Measles vaccine received'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='opv',
            field=models.BooleanField(default=False, help_text='Oral Polio Vaccine received'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='other_conditions',
            field=models.TextField(blank=True, help_text='Other medical conditions not listed above'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='previous_hospitalizations',
            field=models.TextField(blank=True, help_text='Past hospitalizations and dates if known'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='previous_illnesses',
            field=models.TextField(blank=True, help_text='Past illnesses (non‑chronic)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='religion',
            field=models.CharField(blank=True, help_text='Religious affiliation (e.g. Roman Catholic, Islam, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='tt',
            field=models.BooleanField(default=False, help_text='Tetanus Toxoid vaccine received'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='vices',
            field=models.TextField(blank=True, help_text='Smoking, alcohol intake, or other habits'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight in kilograms', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='year_level',
            field=models.CharField(blank=True, help_text='Year level (e.g. 1st Year, 2nd Year, 3rd Year, 4th Year)', max_length=20),
        ),
    ]
