# Generated by Django 6.0.4 on 2026-05-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientprofile_arthritis_patientprofile_asthma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional profile picture (JPG, PNG, WebP)', null=True, upload_to='patients/'),
        ),
    ]
