# Generated by Django 6.0.4 on 2026-05-18 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('patients', '0005_patient_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_end', models.DateField(help_text='When the current academic year officially ends (e.g. 2026-05-31).')),
                ('archive_after_months', models.PositiveIntegerField(default=5, help_text='Months of inactivity after year end before archiving students.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year Settings',
                'verbose_name_plural': 'Academic Year Settings',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the patient was archived.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='archived_reason',
            field=models.CharField(blank=True, help_text='Reason for archiving (e.g. Graduated — no activity after academic year end).', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='expected_graduation_year',
            field=models.PositiveIntegerField(blank=True, help_text='Calculated when student registers based on year level (1st Yr→+4, 2nd Yr→+3, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='True when the patient has been automatically archived (graduated / inactive).'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_archived'], name='patients_pa_is_arch_b8e241_idx'),
        ),
        migrations.AddField(
            model_name='academicyearsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_year_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
