# Generated by Django 6.0.4 on 2026-07-03 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_course'),
        ('patients', '0006_academicyearsettings_patient_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='colleges.course'),
        ),
    ]
