# Generated by Django 6.0.4 on 2026-07-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Temporary password in plaintext (cleared after patient logs in).', max_length=10),
        ),
    ]
