# Generated by Django 6.0.4 on 2026-09-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_temp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(db_index=True, help_text='Student ID / Employee ID / Faculty ID', max_length=30, unique=True),
        ),
    ]
