# Generated by Django 6.0.4 on 2026-05-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_role',
            field=models.CharField(blank=True, choices=[('frontdesk', 'Front Desk'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('patient', 'Patient')], help_text='Role to notify (null = specific user only)', max_length=20, null=True),
        ),
    ]
